### ISSUE TITLE
User Data Failing

### ISSUE THREAD

**Issue by phptek** [phptek/silverstripe-sentry#87]
Related to #85. Since we started using 4.1, there is nothing seen in the "User" section at all apart from the key "Segment" with a vaule of "None".

@jonom Don't supposed you've noticed anything in your Sentry instance?

**Comment by jonom** [comment]
@phptek I've only tried it locally so far but was working there... I got the user tag at the top of the page, and in the User section further down the page it looks the same as before except I got a `J` instead of a `?`.

![image](https://github.com/phptek/silverstripe-sentry/assets/1079425/21eaa9a4-2b6d-436f-8b19-0bb5866573e8)
![image](https://github.com/phptek/silverstripe-sentry/assets/1079425/b8df978d-3d35-406d-9ee1-e8945fed4622)

Could it be to do with privacy scrubbing settings on your Sentry account/project?

I'll update to 4.1 in a live project and let you know how it goes.

**Comment by jonom** [comment]
Yeah it's not working for me anymore either. I'm pretty confused.

It could be a coincidence but I noticed that when I did a composer update sentry/sdk got bumped (3.4 released I think just after my PR), and the version update for sentry/sentry looks screwy...

![image](https://github.com/phptek/silverstripe-sentry/assets/1079425/d04029e9-064f-458a-a6d3-f538e3846696)

I'll try to track it down

**Comment by jonom** [comment]
Took me a while to notice this, but it seems that I'm getting duplicated issues in Sentry. They look a bit different but originate from the same error. I looked back and this was happening before my change as well.

![Screen Shot 2023-05-30 at 10 11 18 PM](https://github.com/phptek/silverstripe-sentry/assets/1079425/08c16917-d97f-4ccc-af5f-4db6f73ef0bc)

The difference is that before my update, both versions of the error had User information, although it wasn't recognised as such. After my update, one of the errors has 'proper' User data, and the other error has none at all.

Are you getting the same behaviour? Seems like addressing the issue duplication may resolve the problem?

**Comment by jonom** [comment]
This just seems to be this issue (https://github.com/phptek/silverstripe-sentry/issues/65)? Seems that the error that gets consciously sent by the module has the user attached, but the auto-sent event from the Sentry SDK doesn't, which would make sense I think.

**Comment by phptek** [comment]
Closing this issue in favour of maintaining #65 as the canonical issue location. Feel free to re-open if you think it needs to be.
